seed: 123

wandb:
  wandb_entity: "koreannn-gangneung-national-university"
  wandb_project: "pytorch-rnn-translator"
  wandb_architecture: "Vanila-RNN-Seq2Seq"

data:
  dataset1: "Helsinki-NLP/opus-100" # 구어체 위주, 짧은 길이 위주
  dataset1_config: "en-ko"
  dataset2: "lemon-mint/korean_english_parallel_wiki_augmented_v1" # 위키피디아 번역문(다양한 도메인 문장, 대부분 길이가 길되 다양한 길이의 문장들이 존재)
  dataset2_valid_ratio: 0.2
  dataset2_test_ratio: 0.2

train:
  h_param:
    learning_rate: 0.001
    epochs: 40
    embedding_dim: 768 # kor-tokenizer의 임베딩 차원에 맞춰서
    hidden_dim: 256
    batch_size: 32
    max_length: 400
    max_new_token: 400
    valid_bleu_sample_size: 2000
    early_stopping:
      patience: 3 # valid loss가 이 횟수만큼 연속으로 개선되지 않을경우, early stopping
      min_delta: 0.005
  model_architecture: "Seq2Seq-with-GRU"

inference:
  max_length: 400
  max_new_token: 400
  batch_size: 32
  checkpoint_path: "checkpoints/best.pt"

model:
  kor_tokenizer: "klue/bert-base"
  en_tokenizer: "google-bert/bert-base-uncased"

