wandb:
  wandb_entity: "koreannn-gangneung-national-university"
  wandb_project: "pytorch-rnn-translator"
  wandb_architecture: "Vanila-RNN-Seq2Seq"
  

train:
  h_param:
    learning_rate: 0.001
    epochs: 10
    embedding_dim: 768 # kor-tokenizer의 임베딩 차원에 맞춰서
    hidden_dim: 768
    batch_size: 256
    max_length: 50
  model_architecture: "Seq2Seq-with-GRU"

inference:
  max_length: 50
  batch_size: 1

model:
  kor_tokenizer: "klue/bert-base"
  en_tokenizer: "google-bert/bert-base-uncased"

