seed: 123


wandb:
  wandb_entity: "koreannn-gangneung-national-university"
  wandb_project: "pytorch-rnn-translator"
  wandb_architecture: "Vanila-RNN-Seq2Seq"


mlflow:
  tracking_uri: "http://127.0.0.1:5002"
  experiment_name: "rnn-translator"
  log_model_weights: true # false일 경우 모델 파일이 MLflow에 올라가지 않음
  run_name: "baseline" # 이번 실험을 짧게 (비우면 MLflow가 랜덤 이름 붙임)
  run_description: "[실험 이름]" # UI Description에 표시
  tags:
    purpose: "baseline" # baseline / ablation / tuning / debug


data:
  dataset1: "Helsinki-NLP/opus-100" # 구어체 위주, 짧은 길이 위주
  dataset1_config: "en-ko"
  dataset2: "lemon-mint/korean_english_parallel_wiki_augmented_v1" # 위키피디아 번역문(다양한 도메인 문장, 대부분 길이가 길되 다양한 길이의 문장들이 존재)
  dataset2_valid_ratio: 0.2
  dataset2_test_ratio: 0.2


model:
  kor_tokenizer: "klue/bert-base"
  en_tokenizer: "google-bert/bert-base-uncased"


train:
  h_param:
    embedding_lr: 1.0e-5
    rnn_attn_fc_lr: 1.0e-3
    epochs: 1 # 40
    embedding_dim: 768 # kor-tokenizer의 임베딩 차원에 맞춰서
    hidden_dim: 768
    init_scheme: "Orthogonal_Xavier" # default / Orthogonal_Xavier
    use_layer_norm: False
    grad_clip_max_norm: 5.0
    batch_size: 32
    max_length: 400
    max_new_token: 400
    valid_bleu_sample_size: 100 # 2000
    early_stopping:
      patience: 3 # valid loss가 이 횟수만큼 연속으로 개선되지 않을경우, early stopping
      min_delta: 0.005
  model_architecture: "Seq2Seq-with-GRU"


inference:
  max_length: 400
  max_new_token: 400
  batch_size: 4
  checkpoint_path: "checkpoints/best.pt"
  decoding_strategy: greedy # greedy / beam / hybrid
  source_run_id: "" # 직접 지정해서 돌릴 경우에만 사용
  sample_size: 1000 # null일 경우 test셋 전체

  beam:
    beam_size: 4
    alpha: 0.6

  hybrid:
    temperature: 0.8
    top_k: 50
    top_p: 0.9

  evaluation:
    use_comet: true


llm:
  model_name: "Qwen/Qwen3-0.6B"
  sample_size: 1000
  latency_sample_size: 200
  prompt:
    version: "v1" # MLflow에 기록될 짧은 이름
    system: "You are a professional translator. Translate Korean text into natural, accurate English."
    user: |
      Translate the following Korean text into English.
      Output only the English translation, without any explanation, notes, or quotation marks.

      {source}
  mlflow_experiment: "llm-translator"
  evaluation:
    use_comet: true

  vllm:
      dtype: "bfloat16"
      max_model_len: 4096 # 프롬프트 + 번역문 최대 길이
      gpu_memory_utilization: 0.85 # vLLM이 미리 잡아둘 GPU 메모리 비율
      enable_prefix_caching: false # KV 캐싱 ON/OFF용 (캐시 재사용으로 인해 latency 측정이 왜곡되지 않도록)

  generation:
    temperature: 0.0
    max_tokens: 1024
    enable_thinking: false

  

